# 第一阶段：构建React应用
FROM node:18 AS builder

WORKDIR /app

# 设置时区
ENV TZ="Asia/Shanghai"

# 第二阶段：构建Nginx服务器
FROM nginx:latest

# 复制构建后的React应用到Nginx默认服务目录
COPY  /dist /usr/share/nginx/html

# 复制自定义的Nginx配置文件到容器中
COPY config/nginx.conf /etc/nginx/nginx.conf

# 暴露端口
EXPOSE 80

# 启动Nginx
CMD ["nginx", "-g", "daemon off;"]
